# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saveTheKingdom', '0002_auto_20170909_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanderer',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
